// Stage 1 realtime-collab POC: expose prosemirror-sync APIs and prove that
// server-side collaborators can edit a document through the same step stream.
// The `components.prosemirrorSync` type is generated by `convex dev` after the
// component is registered in convex.config.ts.

import { ProsemirrorSync } from "@convex-dev/prosemirror-sync";
import {
	getHubbleEditorSchema,
	markdownToTiptapDoc,
	tiptapDocToMarkdown,
} from "@hubble.md/editor";
import { Transform } from "@tiptap/pm/transform";
import { v } from "convex/values";
import { components } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { type MutationCtx, mutation } from "./_generated/server";

const prosemirrorSync = new ProsemirrorSync(components.prosemirrorSync);

function syncIdForLiveDocument(documentId: Id<"documents">): string {
	return `live:${documentId}`;
}

async function assertNoActiveDocumentPath(
	ctx: MutationCtx,
	workspaceId: Id<"workspaces">,
	path: string,
) {
	const matches = await ctx.db
		.query("documents")
		.withIndex("by_workspace_path", (q) =>
			q.eq("workspaceId", workspaceId).eq("path", path),
		)
		.collect();
	if (matches.some((document) => document.deletedAt === undefined)) {
		throw new Error(`Live Document path already exists: ${path}`);
	}
}

// Realtime sync endpoints consumed by the Tiptap client via `useTiptapSync`.
// TODO(stage-3): gate these behind document permission checks (owner/editor/
// viewer). A viewer must never receive `submitSteps`/`submitSnapshot`.
export const {
	getSnapshot,
	submitSnapshot,
	latestVersion,
	getSteps,
	submitSteps,
} = prosemirrorSync.syncApi({
	// checkRead / checkWrite hooks go here in Stage 3.
});

// Read-only markdown projection from the cloud-authoritative ProseMirror doc.
// This is a mutation because prosemirror-sync's `getDoc` API requires a
// mutation-capable Convex context, but this handler does not write.
export const getMarkdownProjection = mutation({
	args: { docId: v.string() },
	handler: async (ctx, { docId }) => {
		const schema = getHubbleEditorSchema();
		const { doc, version } = await prosemirrorSync.getDoc(ctx, docId, schema);
		return {
			docId,
			version,
			markdown: tiptapDocToMarkdown(doc.toJSON()),
		};
	},
});

export const importMarkdownDocument = mutation({
	args: {
		workspaceId: v.id("workspaces"),
		title: v.string(),
		markdown: v.string(),
		path: v.optional(v.string()),
		actor: v.optional(v.string()),
	},
	handler: async (ctx, { workspaceId, title, markdown, path, actor }) => {
		const normalizedTitle = title.trim();
		if (!normalizedTitle) throw new Error("Document title is required");
		const normalizedPath = path?.trim() || undefined;
		if (normalizedPath) {
			await assertNoActiveDocumentPath(ctx, workspaceId, normalizedPath);
		}

		const now = Date.now();
		const documentId = await ctx.db.insert("documents", {
			workspaceId,
			title: normalizedTitle,
			path: normalizedPath,
			createdAt: now,
			createdBy: actor,
			updatedAt: now,
			updatedBy: actor,
		});
		const schema = getHubbleEditorSchema();
		await prosemirrorSync.create(
			ctx,
			syncIdForLiveDocument(documentId),
			markdownToTiptapDoc(markdown),
		);
		const { version } = await prosemirrorSync.getDoc(
			ctx,
			syncIdForLiveDocument(documentId),
			schema,
		);
		return { documentId, syncId: syncIdForLiveDocument(documentId), version };
	},
});

export const exportMarkdownDocument = mutation({
	args: { documentId: v.id("documents") },
	handler: async (ctx, { documentId }) => {
		const document = await ctx.db.get(documentId);
		if (!document || document.deletedAt !== undefined) {
			throw new Error("Live Document not found");
		}
		const syncId = syncIdForLiveDocument(documentId);
		const schema = getHubbleEditorSchema();
		const { doc, version } = await prosemirrorSync.getDoc(ctx, syncId, schema);
		return {
			documentId,
			syncId,
			version,
			markdown: tiptapDocToMarkdown(doc.toJSON()),
		};
	},
});

// --- Agent edit path (Model C) -------------------------------------------
// Proves the decision-gate question "can an agent edit server-side, no browser?"
// `transform` receives the latest doc and returns a ProseMirror Transform/Transaction;
// the change streams to every connected human like any collaborator edit.
//
// The real Model C API (`applyPatch(id, baseRevision, intent)`, outline-targeted
// edits) is built on top of this in Stage 4. This is the minimal proof.
//
export const agentAppendParagraph = mutation({
	args: { docId: v.string(), text: v.string() },
	handler: async (ctx, { docId, text }) => {
		const schema = getHubbleEditorSchema();
		const paragraph = schema.nodes.paragraph;
		if (!paragraph) {
			throw new Error("Hubble editor schema is missing paragraph node");
		}

		await prosemirrorSync.transform(ctx, docId, schema, (doc) => {
			const tr = new Transform(doc);
			const paragraphNode = paragraph.create(
				null,
				text.length > 0 ? schema.text(text) : undefined,
			);
			tr.insert(doc.content.size, paragraphNode);
			return tr;
		});
	},
});
