// Stage 1 realtime-collab POC: expose prosemirror-sync APIs and prove that
// server-side collaborators can edit a document through the same step stream.
// The `components.prosemirrorSync` type is generated by `convex dev` after the
// component is registered in convex.config.ts.

import { ProsemirrorSync } from "@convex-dev/prosemirror-sync";
import {
	getHubbleEditorSchema,
	markdownToTiptapDoc,
	tiptapDocToMarkdown,
} from "@hubble.md/editor";
import { Transform } from "@tiptap/pm/transform";
import { v } from "convex/values";
import { components } from "./_generated/api";
import { type MutationCtx, mutation, type QueryCtx } from "./_generated/server";
import {
	documentIdFromSyncId,
	requireDocumentRead,
	requireDocumentWrite,
} from "./permissions";

const prosemirrorSync = new ProsemirrorSync(components.prosemirrorSync);

function requireLiveDocumentSyncId(syncId: string) {
	const documentId = documentIdFromSyncId(syncId);
	if (!documentId) {
		throw new Error("Unauthorized");
	}
	return documentId;
}

async function checkRead(ctx: QueryCtx, syncId: string) {
	const documentId = requireLiveDocumentSyncId(syncId);
	await requireDocumentRead(ctx, documentId);
}

async function checkWrite(ctx: MutationCtx, syncId: string) {
	const documentId = requireLiveDocumentSyncId(syncId);
	await requireDocumentWrite(ctx, documentId);
}

// Realtime sync endpoints consumed by the Tiptap client via `useTiptapSync`.
export const {
	getSnapshot,
	submitSnapshot,
	latestVersion,
	getSteps,
	submitSteps,
} = prosemirrorSync.syncApi({
	checkRead,
	checkWrite,
});

// --- Agent edit path (Model C) -------------------------------------------
// Proves the decision-gate question "can an agent edit server-side, no browser?"
// `transform` receives the latest doc and returns a ProseMirror Transform/Transaction;
// the change streams to every connected human like any collaborator edit.
//
// The real Model C API (`applyPatch(id, baseRevision, intent)`, outline-targeted
// edits) is built on top of this in Stage 4. This is the minimal proof.
//
export const agentAppendParagraph = mutation({
	args: { docId: v.string(), text: v.string() },
	handler: async (ctx, { docId, text }) => {
		const liveDocumentId = requireLiveDocumentSyncId(docId);
		await requireDocumentWrite(ctx, liveDocumentId);

		const schema = getHubbleEditorSchema();
		const paragraph = schema.nodes.paragraph;
		if (!paragraph) {
			throw new Error("Hubble editor schema is missing paragraph node");
		}

		await prosemirrorSync.transform(ctx, docId, schema, (doc) => {
			const tr = new Transform(doc);
			const paragraphNode = paragraph.create(
				null,
				text.length > 0 ? schema.text(text) : undefined,
			);
			tr.insert(doc.content.size, paragraphNode);
			return tr;
		});

		await ctx.db.patch(liveDocumentId, {
			updatedBy: "Agent",
			updatedAt: Date.now(),
		});
	},
});

function clampOffset(value: number, max: number) {
	if (!Number.isInteger(value) || value < 0 || value > max) {
		throw new Error(`Invalid markdown offset: ${value}`);
	}
	return value;
}

function findSingleOccurrence(haystack: string, needle: string) {
	const index = haystack.indexOf(needle);
	if (index === -1) return null;
	if (haystack.indexOf(needle, index + 1) !== -1) return null;
	return index;
}

function findReconcileRange(
	currentMarkdown: string,
	args: {
		baseMarkdown: string;
		from: number;
		to: number;
	},
) {
	const from = clampOffset(args.from, args.baseMarkdown.length);
	const to = clampOffset(args.to, args.baseMarkdown.length);
	if (from > to) throw new Error("Invalid reconcile range: from is after to");

	const oldText = args.baseMarkdown.slice(from, to);
	const exactIndex =
		oldText.length > 0 ? findSingleOccurrence(currentMarkdown, oldText) : null;
	if (exactIndex !== null) {
		return { from: exactIndex, to: exactIndex + oldText.length };
	}

	// If a collaborator edited inside the same paragraph, the exact old text may
	// no longer exist. Use nearby base context to keep the replacement scoped.
	const beforeContext = args.baseMarkdown.slice(Math.max(0, from - 400), from);
	const afterContext = args.baseMarkdown.slice(
		to,
		Math.min(args.baseMarkdown.length, to + 400),
	);
	const beforeIndex =
		beforeContext.length > 0
			? currentMarkdown.lastIndexOf(beforeContext)
			: from === 0
				? 0
				: -1;
	const afterSearchStart =
		beforeIndex >= 0 ? beforeIndex + beforeContext.length : 0;
	const afterIndex =
		afterContext.length > 0
			? currentMarkdown.indexOf(afterContext, afterSearchStart)
			: to === args.baseMarkdown.length
				? currentMarkdown.length
				: -1;

	if (beforeIndex >= 0 && afterIndex >= 0) {
		return {
			from: beforeIndex + beforeContext.length,
			to: afterIndex,
		};
	}

	throw new Error(
		"Could not map the external markdown range onto the current document",
	);
}

function changedRange(baseText: string, nextText: string) {
	let prefix = 0;
	while (
		prefix < baseText.length &&
		prefix < nextText.length &&
		baseText[prefix] === nextText[prefix]
	) {
		prefix += 1;
	}

	let baseSuffix = baseText.length;
	let nextSuffix = nextText.length;
	while (
		baseSuffix > prefix &&
		nextSuffix > prefix &&
		baseText[baseSuffix - 1] === nextText[nextSuffix - 1]
	) {
		baseSuffix -= 1;
		nextSuffix -= 1;
	}

	if (prefix === baseText.length && prefix === nextText.length) return null;
	return {
		from: prefix,
		to: baseSuffix,
		markdown: nextText.slice(prefix, nextSuffix),
	};
}

function applyTextRange(
	text: string,
	range: { from: number; to: number; markdown: string },
) {
	return text.slice(0, range.from) + range.markdown + text.slice(range.to);
}

function mergeMarkdownRange(
	baseText: string,
	currentText: string,
	externalText: string,
) {
	if (currentText === baseText) return externalText;
	if (externalText === baseText) return currentText;

	const currentChange = changedRange(baseText, currentText);
	const externalChange = changedRange(baseText, externalText);
	if (!currentChange) return externalText;
	if (!externalChange) return currentText;

	if (currentChange.to <= externalChange.from) {
		return applyTextRange(
			applyTextRange(baseText, externalChange),
			currentChange,
		);
	}
	if (externalChange.to <= currentChange.from) {
		return applyTextRange(
			applyTextRange(baseText, currentChange),
			externalChange,
		);
	}
	if (
		currentChange.from === currentChange.to &&
		externalChange.from === externalChange.to &&
		currentChange.from === externalChange.from
	) {
		return applyTextRange(baseText, {
			from: currentChange.from,
			to: currentChange.to,
			markdown: currentChange.markdown + externalChange.markdown,
		});
	}

	return externalText;
}

// Throwaway Decision 6 POC entrypoint. This intentionally bypasses
// documents.applyPatch's stale-revision rejection so an external file save can be
// submitted as a rebasable transform against the latest live ProseMirror doc.
export const reconcileMarkdownRangePoc = mutation({
	args: {
		docId: v.string(),
		baseMarkdown: v.string(),
		from: v.number(),
		to: v.number(),
		markdown: v.string(),
		actor: v.optional(v.string()),
	},
	handler: async (ctx, { docId, baseMarkdown, from, to, markdown, actor }) => {
		const liveDocumentId = requireLiveDocumentSyncId(docId);
		await requireDocumentWrite(ctx, liveDocumentId);

		const schema = getHubbleEditorSchema();
		let nextMarkdown = "";
		await prosemirrorSync.transform(
			ctx,
			docId,
			schema,
			(doc) => {
				const currentMarkdown = tiptapDocToMarkdown(doc.toJSON());
				const range = findReconcileRange(currentMarkdown, {
					baseMarkdown,
					from,
					to,
				});
				const mergedMarkdown = mergeMarkdownRange(
					baseMarkdown.slice(from, to),
					currentMarkdown.slice(range.from, range.to),
					markdown,
				);
				nextMarkdown =
					currentMarkdown.slice(0, range.from) +
					mergedMarkdown +
					currentMarkdown.slice(range.to);
				const nextDoc = schema.nodeFromJSON(markdownToTiptapDoc(nextMarkdown));
				if (doc.eq(nextDoc)) return null;

				const diffStart = doc.content.findDiffStart(nextDoc.content);
				if (diffStart === null) return null;
				const diffEnd = doc.content.findDiffEnd(nextDoc.content);
				if (diffEnd === null) return null;

				const tr = new Transform(doc);
				tr.replace(diffStart, diffEnd.a, nextDoc.slice(diffStart, diffEnd.b));
				return tr;
			},
			{ clientId: actor?.trim() || "file-reconcile-poc" },
		);

		await ctx.db.patch(liveDocumentId, {
			updatedBy: actor?.trim() || "file-reconcile-poc",
			updatedAt: Date.now(),
		});

		return { markdown: nextMarkdown };
	},
});
